<a href="https://colab.research.google.com/github/PeesapatiRohithSharma/Summer_2026/blob/main/gradient_boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
import pandas as pd

In [48]:
class GradientBoosting:
  def __init__(self, alpha = 0.1, max_depth = 4, n_trees = 100):
    self.alpha = alpha
    self.max_depth = max_depth
    self.n_tree = n_trees

    self.trees = []
    self.initial_value = None

  def fit(self, X, y):
    self.initial_value = np.mean(y)
    pred = np.full(len(y), self.initial_value)
    for _ in range(self.n_tree):
      residual = y - pred
      tree = DecisionTreeRegressor(max_depth=self.max_depth)
      tree.fit(X,residual)
      update = tree.predict(X)

      pred += self.alpha*update
      self.trees.append(tree)

  def predict(self, X):
    pred = np.full(X.shape[0], self.initial_value)
    for tree in self.trees:
      update = tree.predict(X)
      pred += self.alpha * update
    return pred

In [49]:
from google.colab import files

In [50]:
data = files.upload()

Saving Silver_Data_2000_2026.csv to Silver_Data_2000_2026 (1).csv

In [51]:
df = pd.read_csv("Silver_Data_2000_2026.csv")

In [52]:
df

            Date       Close        High         Low        Open  Volume
0     2000-08-30    4.930000    4.950000    4.895000    4.950000    2319
1     2000-08-31    5.003000    5.045000    4.920000    4.920000    1612
2     2000-09-01    5.004000    5.035000    4.985000    5.035000    1375
3     2000-09-05    4.998000    5.005000    4.975000    4.990000     856
4     2000-09-06    4.983000    5.000000    4.980000    5.000000     232
...          ...         ...         ...         ...         ...     ...
6375  2026-01-26  115.080002  117.195000  103.220001  105.044998     537
6376  2026-01-27  105.523003  110.519997  103.099998  104.400002     131
6377  2026-01-28  113.111000  114.574997  112.735001  114.574997    1436
6378  2026-01-29  114.037003  121.300003  107.970001  116.889999    1261
6379  2026-01-30   78.530998  118.449997   74.000000  115.885002  306578

[6380 rows x 6 columns]

In [53]:
df["Date"] = pd.to_datetime(df["Date"])

In [54]:
df

           Date       Close        High         Low        Open  Volume
0    2000-08-30    4.930000    4.950000    4.895000    4.950000    2319
1    2000-08-31    5.003000    5.045000    4.920000    4.920000    1612
2    2000-09-01    5.004000    5.035000    4.985000    5.035000    1375
3    2000-09-05    4.998000    5.005000    4.975000    4.990000     856
4    2000-09-06    4.983000    5.000000    4.980000    5.000000     232
...         ...         ...         ...         ...         ...     ...
6375 2026-01-26  115.080002  117.195000  103.220001  105.044998     537
6376 2026-01-27  105.523003  110.519997  103.099998  104.400002     131
6377 2026-01-28  113.111000  114.574997  112.735001  114.574997    1436
6378 2026-01-29  114.037003  121.300003  107.970001  116.889999    1261
6379 2026-01-30   78.530998  118.449997   74.000000  115.885002  306578

[6380 rows x 6 columns]

In [55]:
df = df.sort_values("Date")

In [56]:
df

           Date       Close        High         Low        Open  Volume
0    2000-08-30    4.930000    4.950000    4.895000    4.950000    2319
1    2000-08-31    5.003000    5.045000    4.920000    4.920000    1612
2    2000-09-01    5.004000    5.035000    4.985000    5.035000    1375
3    2000-09-05    4.998000    5.005000    4.975000    4.990000     856
4    2000-09-06    4.983000    5.000000    4.980000    5.000000     232
...         ...         ...         ...         ...         ...     ...
6375 2026-01-26  115.080002  117.195000  103.220001  105.044998     537
6376 2026-01-27  105.523003  110.519997  103.099998  104.400002     131
6377 2026-01-28  113.111000  114.574997  112.735001  114.574997    1436
6378 2026-01-29  114.037003  121.300003  107.970001  116.889999    1261
6379 2026-01-30   78.530998  118.449997   74.000000  115.885002  306578

[6380 rows x 6 columns]

In [57]:
df["input1"] = df["Close"].shift(1)

In [58]:
df

           Date       Close        High  ...        Open  Volume      input1
0    2000-08-30    4.930000    4.950000  ...    4.950000    2319         NaN
1    2000-08-31    5.003000    5.045000  ...    4.920000    1612    4.930000
2    2000-09-01    5.004000    5.035000  ...    5.035000    1375    5.003000
3    2000-09-05    4.998000    5.005000  ...    4.990000     856    5.004000
4    2000-09-06    4.983000    5.000000  ...    5.000000     232    4.998000
...         ...         ...         ...  ...         ...     ...         ...
6375 2026-01-26  115.080002  117.195000  ...  105.044998     537  100.925003
6376 2026-01-27  105.523003  110.519997  ...  104.400002     131  115.080002
6377 2026-01-28  113.111000  114.574997  ...  114.574997    1436  105.523003
6378 2026-01-29  114.037003  121.300003  ...  116.889999    1261  113.111000
6379 2026-01-30   78.530998  118.449997  ...  115.885002  306578  114.037003

[6380 rows x 7 columns]

In [59]:
df["input_2"] = df["Close"].shift(2)
df["input_3"] = df["Close"].shift(3)

In [60]:
df

           Date       Close        High  ...      input1     input_2     input_3
0    2000-08-30    4.930000    4.950000  ...         NaN         NaN         NaN
1    2000-08-31    5.003000    5.045000  ...    4.930000         NaN         NaN
2    2000-09-01    5.004000    5.035000  ...    5.003000    4.930000         NaN
3    2000-09-05    4.998000    5.005000  ...    5.004000    5.003000    4.930000
4    2000-09-06    4.983000    5.000000  ...    4.998000    5.004000    5.003000
...         ...         ...         ...  ...         ...         ...         ...
6375 2026-01-26  115.080002  117.195000  ...  100.925003   95.975998   92.209999
6376 2026-01-27  105.523003  110.519997  ...  115.080002  100.925003   95.975998
6377 2026-01-28  113.111000  114.574997  ...  105.523003  115.080002  100.925003
6378 2026-01-29  114.037003  121.300003  ...  113.111000  105.523003  115.080002
6379 2026-01-30   78.530998  118.449997  ...  114.037003  113.111000  105.523003

[6380 rows x 9 columns]

In [61]:
df = df.dropna()

In [85]:
df["Volume"] = df["Volume"] / df["Volume"].max()

/tmp/ipykernel_638/4076522016.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Volume"] = df["Volume"] / df["Volume"].max()

In [86]:
df

           Date       Close        High  ...      input1     input_2     input_3
3    2000-09-05    4.998000    5.005000  ...    5.004000    5.003000    4.930000
4    2000-09-06    4.983000    5.000000  ...    4.998000    5.004000    5.003000
5    2000-09-07    4.935000    4.980000  ...    4.983000    4.998000    5.004000
6    2000-09-08    4.923000    4.945000  ...    4.935000    4.983000    4.998000
7    2000-09-11    4.885000    4.910000  ...    4.923000    4.935000    4.983000
...         ...         ...         ...  ...         ...         ...         ...
6375 2026-01-26  115.080002  117.195000  ...  100.925003   95.975998   92.209999
6376 2026-01-27  105.523003  110.519997  ...  115.080002  100.925003   95.975998
6377 2026-01-28  113.111000  114.574997  ...  105.523003  115.080002  100.925003
6378 2026-01-29  114.037003  121.300003  ...  113.111000  105.523003  115.080002
6379 2026-01-30   78.530998  118.449997  ...  114.037003  113.111000  105.523003

[6377 rows x 9 columns]

In [87]:
X = df[["input1","input_2", "input_3", "Volume"]].values
y = df["Close"].values

In [88]:
model  = GradientBoosting()

In [89]:
model.fit(X,y)

In [103]:
last_row = df.iloc[-1]
X_tom = np.array([last_row["input1"],last_row["input_2"],last_row["input_3"],last_row["Volume"]])

In [104]:
X_tom.shape

(4,)

In [105]:
model.predict(X_tom.reshape(1,-1))

array([78.8501724])